//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class NextTrip
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public NextTrip()
    {
        this.NextTripItems = new HashSet<NextTripItem>();
    }

    public int Id { get; set; }
    public string Location { get; set; }
    public string ImageUrl { get; set; }
    public string Description { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<NextTripItem> NextTripItems { get; set; }
}

public partial class NextTripItem
{
    public int Id { get; set; }
    public int NextTripId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    public virtual NextTrip NextTrip { get; set; }
}
